import type { TripStatusValue } from "@/lib/contracts";

export type TripWorkspaceTab = {
  id: string;
  label: string;
  parkName: string;
  visitDate: string;
  status: TripStatusValue;
  href: string;
};

type TripWorkspaceTripLike = {
  id: string;
  name: string;
  parkName: string;
  visitDate: string;
  status: TripStatusValue;
  currentStep?: number;
  itineraryCount?: number;
};

const tripStatusPriority: Record<TripStatusValue, number> = {
  DRAFT: 0,
  PLANNED: 1,
  LIVE: 2,
  COMPLETED: 3,
};

function getGenericTripWorkspaceLabel(index: number) {
  return index === 0 ? "Trip planner" : `Trip planner ${index + 1}`;
}

function isAutoGeneratedDraftName(trip: Pick<TripWorkspaceTripLike, "name" | "parkName" | "status">) {
  const trimmedName = trip.name.trim();
  const trimmedParkName = trip.parkName.trim();
  const lowerName = trimmedName.toLowerCase();
  const suffix = trimmedName.slice(trimmedParkName.length).trim();

  return (
    trip.status === "DRAFT" &&
    lowerName.startsWith(`${trimmedParkName.toLowerCase()} `) &&
    /^[A-Z][a-z]{2} \d{1,2}$/.test(suffix)
  );
}

export function isPlannerKickoffDraft(
  trip: Pick<TripWorkspaceTripLike, "status" | "currentStep" | "itineraryCount">
) {
  return trip.status === "DRAFT" && (trip.currentStep ?? 0) === 0 && (trip.itineraryCount ?? 0) === 0;
}

export function getTripWorkspaceHref(trip: Pick<TripWorkspaceTripLike, "id" | "status">) {
  if (trip.status === "DRAFT") {
    return `/trips/new?tripId=${trip.id}`;
  }

  return `/trips/${trip.id}`;
}

export function getTripWorkspaceTabLabel(
  trip: Pick<TripWorkspaceTripLike, "name" | "parkName" | "status">,
  index: number
) {
  const trimmedName = trip.name.trim();

  if (!trimmedName || isAutoGeneratedDraftName(trip)) {
    return getGenericTripWorkspaceLabel(index);
  }

  return trimmedName;
}

export function buildTripWorkspaceTabs<T extends TripWorkspaceTripLike>(trips: T[]): TripWorkspaceTab[] {
  return trips.map((trip, index) => ({
    id: trip.id,
    label: getTripWorkspaceTabLabel(trip, index),
    parkName: trip.parkName,
    visitDate: trip.visitDate,
    status: trip.status,
    href: getTripWorkspaceHref(trip),
  }));
}

export function getTripWorkspaceStatusDetail(trip: Pick<TripWorkspaceTripLike, "status" | "currentStep" | "itineraryCount">) {
  if (trip.status === "DRAFT") {
    if (isPlannerKickoffDraft(trip)) {
      return "Start by telling Mara what you want to plan";
    }

    if ((trip.currentStep ?? 0) > 0) {
      return "Trip details are still being shaped";
    }

    return "Mara is still collecting the basics";
  }

  if (trip.status === "LIVE") {
    return `${trip.itineraryCount ?? 0} routed stops in motion`;
  }

  if (trip.status === "PLANNED") {
    return `${trip.itineraryCount ?? 0} routed stops ready`;
  }

  return `${trip.itineraryCount ?? 0} routed stops completed`;
}

export function pickDefaultTrip<T extends TripWorkspaceTripLike>(trips: T[]) {
  return [...trips].sort((left, right) => tripStatusPriority[left.status] - tripStatusPriority[right.status])[0] ?? null;
}
