import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const park = {
  slug: "aurora-adventure",
  name: "Aurora Adventure Park",
  resort: "Lumen Bay Resort",
  description:
    "A cinematic, waterfront park built around short walks, layered lands, and family-friendly thrill balance.",
  timezone: "America/New_York",
  opensAt: "08:00",
  closesAt: "22:00",
};

const attractions = [
  {
    slug: "comet-run",
    name: "Comet Run",
    category: "RIDE",
    zone: "Launch Pier",
    description: "A terrain-hugging coaster that rewards rope drop with a dramatic bayfront sprint.",
    thrillLevel: 5,
    minHeight: 48,
    kidFriendly: false,
    indoor: false,
    familyFriendly: false,
    durationMinutes: 4,
    xCoord: 12,
    yCoord: 82,
    tags: ["coaster", "speed", "must-do"],
    typicalWaitProfile: { 8: 20, 9: 34, 10: 48, 11: 61, 12: 72, 13: 79, 14: 82, 15: 78, 16: 70, 17: 64, 18: 56, 19: 43, 20: 31, 21: 18 },
  },
  {
    slug: "nebula-drift",
    name: "Nebula Drift",
    category: "RIDE",
    zone: "Celestial Harbor",
    description: "A luminous dark ride through floating observatories and drifting sea stars.",
    thrillLevel: 2,
    minHeight: null,
    kidFriendly: true,
    indoor: true,
    familyFriendly: true,
    durationMinutes: 8,
    xCoord: 18,
    yCoord: 64,
    tags: ["dark-ride", "family", "indoors"],
    typicalWaitProfile: { 8: 9, 9: 16, 10: 28, 11: 38, 12: 46, 13: 51, 14: 55, 15: 50, 16: 45, 17: 39, 18: 32, 19: 26, 20: 17, 21: 9 },
  },
  {
    slug: "skygarden-flyers",
    name: "Skygarden Flyers",
    category: "RIDE",
    zone: "Starlight Gardens",
    description: "A suspended family spinner with panoramic swings above the floral canopy.",
    thrillLevel: 3,
    minHeight: null,
    kidFriendly: true,
    indoor: false,
    familyFriendly: true,
    durationMinutes: 5,
    xCoord: 48,
    yCoord: 22,
    tags: ["spinner", "outdoor", "aerial"],
    typicalWaitProfile: { 8: 6, 9: 12, 10: 20, 11: 26, 12: 31, 13: 33, 14: 34, 15: 33, 16: 29, 17: 24, 18: 20, 19: 16, 20: 10, 21: 6 },
  },
  {
    slug: "solstice-speedway",
    name: "Solstice Speedway",
    category: "RIDE",
    zone: "Ignition District",
    description: "A launched desert-road coaster with bright airtime hills and a fast unload.",
    thrillLevel: 4,
    minHeight: 44,
    kidFriendly: false,
    indoor: false,
    familyFriendly: true,
    durationMinutes: 6,
    xCoord: 76,
    yCoord: 48,
    tags: ["coaster", "launch", "speed"],
    typicalWaitProfile: { 8: 16, 9: 28, 10: 42, 11: 55, 12: 63, 13: 69, 14: 71, 15: 68, 16: 60, 17: 53, 18: 45, 19: 34, 20: 23, 21: 14 },
  },
  {
    slug: "lantern-rapids",
    name: "Lantern Rapids",
    category: "RIDE",
    zone: "Harbor Wilds",
    description: "A winding family raft ride through glowing caverns and misty arches.",
    thrillLevel: 3,
    minHeight: null,
    kidFriendly: true,
    indoor: false,
    familyFriendly: true,
    durationMinutes: 10,
    xCoord: 62,
    yCoord: 76,
    tags: ["water", "family", "outdoor"],
    typicalWaitProfile: { 8: 5, 9: 10, 10: 18, 11: 29, 12: 41, 13: 49, 14: 53, 15: 55, 16: 52, 17: 44, 18: 34, 19: 24, 20: 14, 21: 8 },
  },
  {
    slug: "tidepool-tots",
    name: "Tidepool Tots",
    category: "PLAY",
    zone: "Harbor Wilds",
    description: "A splash-safe marine play garden sized for preschool energy and stroller breaks.",
    thrillLevel: 1,
    minHeight: null,
    kidFriendly: true,
    indoor: false,
    familyFriendly: true,
    durationMinutes: 20,
    xCoord: 68,
    yCoord: 86,
    tags: ["playground", "toddlers", "shade"],
    typicalWaitProfile: { 8: 1, 9: 3, 10: 5, 11: 6, 12: 7, 13: 8, 14: 8, 15: 8, 16: 7, 17: 6, 18: 5, 19: 4, 20: 2, 21: 1 },
  },
  {
    slug: "eclipse-drop",
    name: "Eclipse Drop",
    category: "RIDE",
    zone: "Ignition District",
    description: "A punchy vertical drop tower with harbor views at the top and a hard queue penalty later.",
    thrillLevel: 5,
    minHeight: 52,
    kidFriendly: false,
    indoor: false,
    familyFriendly: false,
    durationMinutes: 3,
    xCoord: 84,
    yCoord: 42,
    tags: ["drop", "intense", "must-do"],
    typicalWaitProfile: { 8: 18, 9: 32, 10: 48, 11: 60, 12: 69, 13: 75, 14: 78, 15: 74, 16: 69, 17: 61, 18: 51, 19: 38, 20: 26, 21: 15 },
  },
  {
    slug: "harbor-carousel",
    name: "Harbor Carousel",
    category: "RIDE",
    zone: "Celestial Harbor",
    description: "A double-decker carousel with sea lantern mounts and consistently low waits.",
    thrillLevel: 1,
    minHeight: null,
    kidFriendly: true,
    indoor: false,
    familyFriendly: true,
    durationMinutes: 6,
    xCoord: 28,
    yCoord: 58,
    tags: ["gentle", "classic", "family"],
    typicalWaitProfile: { 8: 4, 9: 7, 10: 12, 11: 18, 12: 21, 13: 24, 14: 24, 15: 23, 16: 21, 17: 17, 18: 14, 19: 11, 20: 7, 21: 4 },
  },
  {
    slug: "moonlit-manor",
    name: "Moonlit Manor",
    category: "RIDE",
    zone: "Moon Market",
    description: "A lightly spooky mansion ride with practical sets and no height restriction.",
    thrillLevel: 2,
    minHeight: null,
    kidFriendly: true,
    indoor: true,
    familyFriendly: true,
    durationMinutes: 9,
    xCoord: 42,
    yCoord: 58,
    tags: ["dark-ride", "story", "indoors"],
    typicalWaitProfile: { 8: 8, 9: 14, 10: 22, 11: 30, 12: 37, 13: 41, 14: 44, 15: 42, 16: 38, 17: 31, 18: 26, 19: 20, 20: 13, 21: 8 },
  },
  {
    slug: "starfall-racers",
    name: "Starfall Racers",
    category: "RIDE",
    zone: "Launch Pier",
    description: "Twin dueling coasters with a low walk from rope drop and big afternoon spikes.",
    thrillLevel: 4,
    minHeight: 48,
    kidFriendly: false,
    indoor: false,
    familyFriendly: false,
    durationMinutes: 4,
    xCoord: 20,
    yCoord: 94,
    tags: ["coaster", "dueling", "speed"],
    typicalWaitProfile: { 8: 16, 9: 28, 10: 42, 11: 55, 12: 63, 13: 69, 14: 71, 15: 68, 16: 60, 17: 53, 18: 45, 19: 34, 20: 23, 21: 14 },
  },
  {
    slug: "cloudline-express",
    name: "Cloudline Express",
    category: "RIDE",
    zone: "Sky Loop",
    description: "A scenic elevated tram that doubles as a low-effort way to reposition the family.",
    thrillLevel: 1,
    minHeight: null,
    kidFriendly: true,
    indoor: false,
    familyFriendly: true,
    durationMinutes: 12,
    xCoord: 50,
    yCoord: 50,
    tags: ["transport", "gentle", "family"],
    typicalWaitProfile: { 8: 3, 9: 5, 10: 8, 11: 10, 12: 13, 13: 14, 14: 14, 15: 14, 16: 13, 17: 11, 18: 10, 19: 8, 20: 5, 21: 3 },
  },
  {
    slug: "rocket-reef",
    name: "Rocket Reef",
    category: "RIDE",
    zone: "Harbor Wilds",
    description: "A giant swing ride over the lagoon that gets extra sensitive to weather changes.",
    thrillLevel: 4,
    minHeight: 46,
    kidFriendly: false,
    indoor: false,
    familyFriendly: true,
    durationMinutes: 5,
    xCoord: 82,
    yCoord: 82,
    tags: ["thrill", "outdoor", "swing"],
    typicalWaitProfile: { 8: 16, 9: 28, 10: 42, 11: 55, 12: 63, 13: 69, 14: 71, 15: 68, 16: 60, 17: 53, 18: 45, 19: 34, 20: 23, 21: 14 },
  },
  {
    slug: "firefly-forest-trail",
    name: "Firefly Forest Trail",
    category: "SHOW",
    zone: "Starlight Gardens",
    description: "A shaded walk-through of bioluminescent installations and ambient music pockets.",
    thrillLevel: 1,
    minHeight: null,
    kidFriendly: true,
    indoor: false,
    familyFriendly: true,
    durationMinutes: 15,
    xCoord: 56,
    yCoord: 12,
    tags: ["show", "walkthrough", "shade"],
    typicalWaitProfile: { 8: 2, 9: 4, 10: 6, 11: 8, 12: 11, 13: 13, 14: 13, 15: 14, 16: 12, 17: 10, 18: 9, 19: 6, 20: 4, 21: 2 },
  },
  {
    slug: "aurora-theater-spectacular",
    name: "Aurora Theater Spectacular",
    category: "SHOW",
    zone: "Celestial Harbor",
    description: "A seated indoor projection show that works well as a mid-afternoon cool-down.",
    thrillLevel: 1,
    minHeight: null,
    kidFriendly: true,
    indoor: true,
    familyFriendly: true,
    durationMinutes: 30,
    xCoord: 34,
    yCoord: 34,
    tags: ["show", "indoors", "air-conditioned"],
    typicalWaitProfile: { 8: 0, 9: 0, 10: 8, 11: 10, 12: 10, 13: 12, 14: 12, 15: 12, 16: 10, 17: 10, 18: 10, 19: 8, 20: 0, 21: 0 },
  },
  {
    slug: "cosmo-quest",
    name: "Cosmo Quest",
    category: "RIDE",
    zone: "Moon Market",
    description: "A blaster-style adventure with high throughput and strong kid compatibility.",
    thrillLevel: 2,
    minHeight: null,
    kidFriendly: true,
    indoor: true,
    familyFriendly: true,
    durationMinutes: 7,
    xCoord: 58,
    yCoord: 44,
    tags: ["interactive", "family", "indoors"],
    typicalWaitProfile: { 8: 11, 9: 20, 10: 30, 11: 41, 12: 49, 13: 55, 14: 58, 15: 56, 16: 51, 17: 43, 18: 35, 19: 27, 20: 18, 21: 10 },
  },
  {
    slug: "pebble-creek-play-yard",
    name: "Pebble Creek Play Yard",
    category: "PLAY",
    zone: "Harbor Wilds",
    description: "A quiet climber-and-sensory zone sized for recharge breaks and younger siblings.",
    thrillLevel: 1,
    minHeight: null,
    kidFriendly: true,
    indoor: false,
    familyFriendly: true,
    durationMinutes: 18,
    xCoord: 54,
    yCoord: 86,
    tags: ["playground", "quiet", "shade"],
    typicalWaitProfile: { 8: 1, 9: 3, 10: 5, 11: 6, 12: 7, 13: 8, 14: 8, 15: 8, 16: 7, 17: 6, 18: 5, 19: 4, 20: 2, 21: 1 },
  },
  {
    slug: "boardwalk-bento",
    name: "Boardwalk Bento",
    category: "DINING",
    zone: "Celestial Harbor",
    description: "Fast rice bowls and grilled skewers near the harbor entrance.",
    thrillLevel: 1,
    minHeight: null,
    kidFriendly: true,
    indoor: true,
    familyFriendly: true,
    durationMinutes: 40,
    xCoord: 24,
    yCoord: 42,
    tags: ["quick-service", "asian"],
    typicalWaitProfile: { 8: 0, 9: 0, 10: 4, 11: 10, 12: 22, 13: 19, 14: 14, 15: 11, 16: 12, 17: 17, 18: 21, 19: 16, 20: 9, 21: 3 },
  },
  {
    slug: "sunflare-tacos",
    name: "Sunflare Tacos",
    category: "DINING",
    zone: "Ignition District",
    description: "Tacos, grain bowls, and shaded outdoor tables near the speedway exit.",
    thrillLevel: 1,
    minHeight: null,
    kidFriendly: true,
    indoor: false,
    familyFriendly: true,
    durationMinutes: 35,
    xCoord: 74,
    yCoord: 56,
    tags: ["quick-service", "mexican"],
    typicalWaitProfile: { 8: 0, 9: 0, 10: 4, 11: 10, 12: 22, 13: 19, 14: 14, 15: 11, 16: 12, 17: 17, 18: 21, 19: 16, 20: 9, 21: 3 },
  },
  {
    slug: "harbor-hearth",
    name: "Harbor Hearth",
    category: "DINING",
    zone: "Launch Pier",
    description: "A relaxed sit-down hall for flatbreads, roast chicken, and an early dinner reset.",
    thrillLevel: 1,
    minHeight: null,
    kidFriendly: true,
    indoor: true,
    familyFriendly: true,
    durationMinutes: 45,
    xCoord: 14,
    yCoord: 68,
    tags: ["table-service", "comfort"],
    typicalWaitProfile: { 8: 0, 9: 0, 10: 4, 11: 10, 12: 22, 13: 19, 14: 14, 15: 11, 16: 12, 17: 17, 18: 21, 19: 16, 20: 9, 21: 3 },
  },
  {
    slug: "twilight-treats",
    name: "Twilight Treats",
    category: "DINING",
    zone: "Moon Market",
    description: "Soft-serve, churros, and late-day sugar for the final push.",
    thrillLevel: 1,
    minHeight: null,
    kidFriendly: true,
    indoor: true,
    familyFriendly: true,
    durationMinutes: 20,
    xCoord: 44,
    yCoord: 68,
    tags: ["snacks", "dessert"],
    typicalWaitProfile: { 8: 0, 9: 0, 10: 2, 11: 4, 12: 6, 13: 8, 14: 9, 15: 9, 16: 8, 17: 7, 18: 8, 19: 7, 20: 5, 21: 2 },
  },
];

async function seedParkCatalog() {
  const seededPark = await prisma.park.upsert({
    where: { slug: park.slug },
    update: {
      name: park.name,
      resort: park.resort,
      description: park.description,
      timezone: park.timezone,
      opensAt: park.opensAt,
      closesAt: park.closesAt,
    },
    create: park,
  });

  for (const attraction of attractions) {
    await prisma.attraction.upsert({
      where: {
        parkId_slug: {
          parkId: seededPark.id,
          slug: attraction.slug,
        },
      },
      update: {
        name: attraction.name,
        category: attraction.category,
        zone: attraction.zone,
        description: attraction.description,
        thrillLevel: attraction.thrillLevel,
        minHeight: attraction.minHeight,
        kidFriendly: attraction.kidFriendly,
        indoor: attraction.indoor,
        familyFriendly: attraction.familyFriendly,
        durationMinutes: attraction.durationMinutes,
        xCoord: attraction.xCoord,
        yCoord: attraction.yCoord,
        tags: attraction.tags,
        typicalWaitProfile: attraction.typicalWaitProfile,
        status: "OPEN",
      },
      create: {
        parkId: seededPark.id,
        slug: attraction.slug,
        name: attraction.name,
        category: attraction.category,
        zone: attraction.zone,
        description: attraction.description,
        thrillLevel: attraction.thrillLevel,
        minHeight: attraction.minHeight,
        kidFriendly: attraction.kidFriendly,
        indoor: attraction.indoor,
        familyFriendly: attraction.familyFriendly,
        durationMinutes: attraction.durationMinutes,
        xCoord: attraction.xCoord,
        yCoord: attraction.yCoord,
        tags: attraction.tags,
        typicalWaitProfile: attraction.typicalWaitProfile,
        status: "OPEN",
      },
    });
  }

  console.log(`Seeded park catalog for ${seededPark.name} with ${attractions.length} attractions.`);
}

seedParkCatalog()
  .catch((error) => {
    console.error("Failed to seed the park catalog.");
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

