"use client";

import { useRouter } from "next/navigation";
import {
  CalendarDays,
  ChevronDown,
  LoaderCircle,
  MapPinned,
  Save,
  Sparkles,
  Users,
  type LucideIcon,
} from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState, useTransition } from "react";

import type { ParkCatalogDto, TripDetailDto } from "@/lib/contracts";
import { cn } from "@/lib/utils";

import { PlannerSectionKicker } from "@/components/trip/planner-section-kicker";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

type TripFormValues = {
  name: string;
  visitDate: string;
  partySizeInput: string;
  kidsAgesInput: string;
  thrillTolerance: "" | "LOW" | "MEDIUM" | "HIGH";
  walkingTolerance: "" | "LOW" | "MEDIUM" | "HIGH";
  startTime: string;
  breakStart: string;
  breakEnd: string;
  mustDoRideIds: string[];
  preferredRideTypes: string[];
  diningPreferences: string[];
};

type SaveState = "idle" | "saving" | "saved" | "error";

type PersistableDraftPayload = Partial<{
  name: string;
  visitDate: string;
  partySize: number;
  kidsAges: number[];
  thrillTolerance: "LOW" | "MEDIUM" | "HIGH";
  walkingTolerance: "LOW" | "MEDIUM" | "HIGH";
  preferredRideTypes: string[];
  mustDoRideIds: string[];
  diningPreferences: string[];
  startTime: string;
  breakStart: string;
  breakEnd: string;
  currentStep: number;
}>;

type PersistDraftOptions = {
  keepalive?: boolean;
  skipStateUpdates?: boolean;
};

const inputClassName =
  "mt-2 w-full rounded-[22px] border border-slate-200 bg-white px-4 py-3 text-slate-950 outline-none ring-0 transition focus:border-[#1b6b63]/40";

const thrillOptions = [
  {
    value: "LOW",
    label: "Low thrill",
    description: "Keep the day gentle and easy to say yes to.",
  },
  {
    value: "MEDIUM",
    label: "Balanced mix",
    description: "Blend family rides with a few stronger peaks.",
  },
  {
    value: "HIGH",
    label: "Big headliners",
    description: "Let the plan chase the strongest attractions.",
  },
] as const;

const walkingOptions = [
  {
    value: "LOW",
    label: "Compact path",
    description: "Stay tighter and avoid long crisscrosses.",
  },
  {
    value: "MEDIUM",
    label: "Balanced route",
    description: "Walk some extra distance when timing improves.",
  },
  {
    value: "HIGH",
    label: "Go anywhere",
    description: "Cover more ground if the payoff is worth it.",
  },
] as const;

function toggleSelection(values: string[], value: string) {
  return values.includes(value) ? values.filter((item) => item !== value) : [...values, value];
}

function parseKidsAges(input: string) {
  return input
    .split(",")
    .map((value) => Number(value.trim()))
    .filter((value) => Number.isFinite(value) && value >= 0 && value <= 17);
}

function parsePartySize(input: string) {
  const trimmed = input.trim();
  if (!trimmed) {
    return null;
  }

  const value = Number(trimmed);
  if (!Number.isInteger(value) || value < 1 || value > 12) {
    return null;
  }

  return value;
}

function formatSavedAt(date: Date | null) {
  if (!date) {
    return "Changes save automatically";
  }

  return `Saved at ${new Intl.DateTimeFormat("en-US", {
    hour: "numeric",
    minute: "2-digit",
  }).format(date)}`;
}

function isAutoGeneratedDraftName(name: string, parkName: string) {
  const trimmedName = name.trim();
  const trimmedParkName = parkName.trim();
  const lowerName = trimmedName.toLowerCase();
  const suffix = trimmedName.slice(trimmedParkName.length).trim();

  return (
    lowerName.startsWith(`${trimmedParkName.toLowerCase()} `) &&
    /^[A-Z][a-z]{2} \d{1,2}$/.test(suffix)
  );
}

function shouldStartWithBlankDetails(initialTrip: TripDetailDto) {
  return (
    initialTrip.status === "DRAFT" &&
    initialTrip.currentStep === 0 &&
    initialTrip.itinerary.length === 0 &&
    isAutoGeneratedDraftName(initialTrip.name, initialTrip.park.name)
  );
}

function buildInitialValues(initialTrip: TripDetailDto, startBlank: boolean): TripFormValues {
  if (startBlank) {
    return {
      name: "",
      visitDate: "",
      partySizeInput: "",
      kidsAgesInput: "",
      thrillTolerance: "",
      walkingTolerance: "",
      startTime: "",
      breakStart: "",
      breakEnd: "",
      mustDoRideIds: [],
      preferredRideTypes: [],
      diningPreferences: [],
    };
  }

  return {
    name: initialTrip.name,
    visitDate: initialTrip.visitDate,
    partySizeInput: String(initialTrip.partyProfile.partySize),
    kidsAgesInput: initialTrip.partyProfile.kidsAges.join(", "),
    thrillTolerance: initialTrip.partyProfile.thrillTolerance,
    walkingTolerance: initialTrip.partyProfile.walkingTolerance,
    startTime: initialTrip.partyProfile.startTime,
    breakStart: initialTrip.partyProfile.breakStart ?? "",
    breakEnd: initialTrip.partyProfile.breakEnd ?? "",
    mustDoRideIds: initialTrip.partyProfile.mustDoRideIds,
    preferredRideTypes: initialTrip.partyProfile.preferredRideTypes,
    diningPreferences: initialTrip.partyProfile.diningPreferences,
  };
}

function buildPersistableDraftPayload(values: TripFormValues): PersistableDraftPayload | null {
  const payload: PersistableDraftPayload = {};
  const trimmedName = values.name.trim();
  const parsedPartySize = parsePartySize(values.partySizeInput);
  const parsedKidsAges = parseKidsAges(values.kidsAgesInput);

  if (trimmedName.length >= 3) {
    payload.name = trimmedName;
  }

  if (values.visitDate) {
    payload.visitDate = values.visitDate;
  }

  if (parsedPartySize !== null) {
    payload.partySize = parsedPartySize;
  }

  if (values.kidsAgesInput.trim()) {
    payload.kidsAges = parsedKidsAges;
  }

  if (values.thrillTolerance) {
    payload.thrillTolerance = values.thrillTolerance;
  }

  if (values.walkingTolerance) {
    payload.walkingTolerance = values.walkingTolerance;
  }

  if (values.startTime) {
    payload.startTime = values.startTime;
  }

  if (values.breakStart && values.breakEnd && values.breakStart < values.breakEnd) {
    payload.breakStart = values.breakStart;
    payload.breakEnd = values.breakEnd;
  }

  const hasMeaningfulValues = Object.keys(payload).length > 0;
  const hasCollectionSelections =
    values.mustDoRideIds.length > 0 ||
    values.preferredRideTypes.length > 0 ||
    values.diningPreferences.length > 0;
  const shouldClearBreakWindow = !values.breakStart && !values.breakEnd;

  if (!hasMeaningfulValues && !hasCollectionSelections) {
    return null;
  }

  payload.mustDoRideIds = values.mustDoRideIds;
  payload.preferredRideTypes = values.preferredRideTypes;
  payload.diningPreferences = values.diningPreferences;

  if (shouldClearBreakWindow) {
    payload.breakStart = "";
    payload.breakEnd = "";
  }

  payload.currentStep = 1;
  return payload;
}

function getMissingRequiredFields(values: TripFormValues) {
  const missingFields: string[] = [];

  if (!values.visitDate) {
    missingFields.push("visit date");
  }

  if (parsePartySize(values.partySizeInput) === null) {
    missingFields.push("group size");
  }

  if (!values.thrillTolerance) {
    missingFields.push("thrill tolerance");
  }

  if (!values.walkingTolerance) {
    missingFields.push("walking tolerance");
  }

  if (!values.startTime) {
    missingFields.push("arrival time");
  }

  if ((values.breakStart && !values.breakEnd) || (!values.breakStart && values.breakEnd)) {
    missingFields.push("complete break window");
  }

  if (values.breakStart && values.breakEnd && values.breakStart >= values.breakEnd) {
    missingFields.push("valid break window");
  }

  return missingFields;
}

export function TripForm({ catalog, initialTrip }: { catalog: ParkCatalogDto; initialTrip: TripDetailDto }) {
  const router = useRouter();
  const [isGenerating, startGeneration] = useTransition();
  const startsBlank = useMemo(() => shouldStartWithBlankDetails(initialTrip), [initialTrip]);
  const initialValues = useMemo(() => buildInitialValues(initialTrip, startsBlank), [initialTrip, startsBlank]);

  const [values, setValues] = useState<TripFormValues>(initialValues);
  const [saveState, setSaveState] = useState<SaveState>("idle");
  const [saveError, setSaveError] = useState<string | null>(null);
  const [lastSavedAt, setLastSavedAt] = useState<Date | null>(null);
  const hasHydrated = useRef(false);
  const valuesRef = useRef(initialValues);
  const lastSavedPayload = useRef(JSON.stringify(buildPersistableDraftPayload(initialValues) ?? {}));
  const inFlightSnapshot = useRef<string | null>(null);

  const persistDraft = useCallback(
    async (draftValues: TripFormValues = valuesRef.current, options: PersistDraftOptions = {}) => {
      const payload = buildPersistableDraftPayload(draftValues);
      const snapshot = JSON.stringify(payload ?? {});

      if (snapshot === lastSavedPayload.current || snapshot === inFlightSnapshot.current) {
        return true;
      }

      if (!payload) {
        return true;
      }

      if (!options.skipStateUpdates) {
        setSaveState("saving");
        setSaveError(null);
      }

      inFlightSnapshot.current = snapshot;

      try {
        const response = await fetch(`/api/trips/${initialTrip.id}`, {
          method: "PATCH",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(payload),
          keepalive: options.keepalive,
        });

        if (!response.ok) {
          const result = (await response.json()) as { error?: string };

          if (!options.skipStateUpdates) {
            setSaveState("error");
            setSaveError(result.error || "Unable to save your trip details.");
          }

          return false;
        }

        lastSavedPayload.current = snapshot;

        if (!options.skipStateUpdates) {
          setSaveState("saved");
          setLastSavedAt(new Date());
        }

        return true;
      } catch (error) {
        if (!options.skipStateUpdates) {
          setSaveState("error");
          setSaveError(error instanceof Error ? error.message : "Unable to save your trip details.");
        }

        return false;
      } finally {
        if (inFlightSnapshot.current === snapshot) {
          inFlightSnapshot.current = null;
        }
      }
    },
    [initialTrip.id]
  );

  useEffect(() => {
    valuesRef.current = values;
  }, [values]);

  useEffect(() => {
    if (!hasHydrated.current) {
      hasHydrated.current = true;
      return;
    }

    const timeout = window.setTimeout(() => {
      void persistDraft(values);
    }, 400);

    return () => window.clearTimeout(timeout);
  }, [persistDraft, values]);

  useEffect(() => {
    const flushPendingDraft = () => {
      void persistDraft(valuesRef.current, { keepalive: true, skipStateUpdates: true });
    };

    const handleVisibilityChange = () => {
      if (document.visibilityState === "hidden") {
        flushPendingDraft();
      }
    };

    window.addEventListener("pagehide", flushPendingDraft);
    document.addEventListener("visibilitychange", handleVisibilityChange);

    return () => {
      window.removeEventListener("pagehide", flushPendingDraft);
      document.removeEventListener("visibilitychange", handleVisibilityChange);
    };
  }, [persistDraft]);

  function updateValues(nextValues: Partial<TripFormValues>) {
    setSaveError(null);
    setSaveState("idle");
    setValues((current) => ({
      ...current,
      ...nextValues,
    }));
  }

  const selectedMustDos = catalog.mustDoOptions.filter((attraction) => values.mustDoRideIds.includes(attraction.id));
  const kidsSummary = parseKidsAges(values.kidsAgesInput);
  const parsedPartySize = parsePartySize(values.partySizeInput);
  const summaryCards = [
    {
      label: "Planner",
      value: values.name.trim() || "Add a trip name",
      detail: catalog.park.name,
      icon: MapPinned,
    },
    {
      label: "Date",
      value: values.visitDate || "Choose a visit date",
      detail: values.startTime ? `Start ${values.startTime}` : "Set arrival time",
      icon: CalendarDays,
    },
    {
      label: "Group",
      value: parsedPartySize ? `${parsedPartySize} ${parsedPartySize === 1 ? "guest" : "guests"}` : "Set group size",
      detail: kidsSummary.length ? `Kids ${kidsSummary.join(", ")}` : "No kids saved",
      icon: Users,
    },
    {
      label: "Priorities",
      value: values.thrillTolerance ? `${values.thrillTolerance.toLowerCase()} thrill` : "Set priorities",
      detail: selectedMustDos.length ? `${selectedMustDos.length} must-dos saved` : "No must-dos yet",
      icon: Sparkles,
    },
  ];

  async function handleGenerate() {
    const missingFields = getMissingRequiredFields(values);
    if (missingFields.length) {
      setSaveState("error");
      setSaveError(`Add ${missingFields.join(", ")} before building the trip plan.`);
      return;
    }

    startGeneration(async () => {
      const saved = await persistDraft();
      if (!saved) {
        return;
      }

      const response = await fetch(`/api/trips/${initialTrip.id}/generate`, {
        method: "POST",
      });

      if (!response.ok) {
        const result = (await response.json()) as { error?: string };
        setSaveState("error");
        setSaveError(result.error || "Unable to build the trip plan.");
        return;
      }

      router.push(`/trips/${initialTrip.id}`);
      router.refresh();
    });
  }

  async function handleSave() {
    const saved = await persistDraft();
    if (!saved) {
      return;
    }

    if (!buildPersistableDraftPayload(values)) {
      setSaveState("error");
      setSaveError("Start with at least one trip detail before saving.");
    }
  }

  return (
    <Card className="p-6 sm:p-7" data-tour-id="trip-details-card" onBlurCapture={() => void persistDraft(valuesRef.current)}>
      <div className="flex flex-col gap-4 border-b border-slate-200/80 pb-5 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <PlannerSectionKicker emoji="🗂️" label="Trip details" tone="teal" />
          <h2 className="mt-3 font-[family-name:var(--font-space-grotesk)] text-3xl font-semibold tracking-tight text-slate-950">
            Trip basics
          </h2>
          <p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600">
            Changes save automatically as you fill this in. Open Advanced when you need more control.
          </p>
        </div>
        <div className="flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm text-slate-600">
          <Save className="h-4 w-4 text-teal-700" />
          <span>
            {saveState === "saving"
              ? "Saving details..."
              : saveState === "error"
                ? saveError || "Unable to save your trip details."
                : formatSavedAt(lastSavedAt)}
          </span>
        </div>
      </div>

      <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
        {summaryCards.map((card) => (
          <SnapshotCard key={card.label} label={card.label} value={card.value} detail={card.detail} icon={card.icon} />
        ))}
      </div>

      {saveError && saveState === "error" ? (
        <p className="mt-4 rounded-[22px] border border-[#efc1bc] bg-[#fff0ee] px-4 py-3 text-sm text-[#b14b41]">{saveError}</p>
      ) : null}

      <details className="group mt-6 rounded-[28px] border border-slate-200 bg-slate-50 [&_summary::-webkit-details-marker]:hidden">
        <summary className="flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-5 sm:px-6">
          <div>
            <PlannerSectionKicker emoji="🛠️" label="Advanced details" tone="amber" />
            <p className="mt-2 text-sm text-slate-600">Open more settings.</p>
          </div>
          <ChevronDown className="h-5 w-5 text-slate-500 transition group-open:rotate-180" />
        </summary>

        <div className="border-t border-slate-200 px-5 py-5 sm:px-6 sm:py-6">
          <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
            <label className="text-sm text-slate-600">
              Trip name
              <input
                value={values.name}
                onChange={(event) => updateValues({ name: event.currentTarget.value })}
                className={inputClassName}
                placeholder="Weekend park day"
              />
            </label>

            <label className="text-sm text-slate-600">
              Visit date
              <input
                type="date"
                value={values.visitDate}
                onChange={(event) => updateValues({ visitDate: event.currentTarget.value })}
                className={inputClassName}
              />
            </label>

            <label className="text-sm text-slate-600">
              Arrival time
              <input
                type="time"
                value={values.startTime}
                onChange={(event) => updateValues({ startTime: event.currentTarget.value })}
                className={inputClassName}
              />
            </label>

            <label className="text-sm text-slate-600">
              Party size
              <input
                type="number"
                min={1}
                max={12}
                value={values.partySizeInput}
                onChange={(event) => updateValues({ partySizeInput: event.currentTarget.value })}
                className={inputClassName}
                placeholder="4"
              />
            </label>

            <label className="text-sm text-slate-600">
              Kids ages
              <input
                value={values.kidsAgesInput}
                onChange={(event) => updateValues({ kidsAgesInput: event.currentTarget.value })}
                className={inputClassName}
                placeholder="6, 9"
              />
            </label>

            <div className="grid gap-5 sm:grid-cols-2 xl:col-span-1">
              <label className="text-sm text-slate-600">
                Break starts
                <input
                  type="time"
                  value={values.breakStart}
                  onChange={(event) => updateValues({ breakStart: event.currentTarget.value })}
                  className={inputClassName}
                />
              </label>
              <label className="text-sm text-slate-600">
                Break ends
                <input
                  type="time"
                  value={values.breakEnd}
                  onChange={(event) => updateValues({ breakEnd: event.currentTarget.value })}
                  className={inputClassName}
                />
              </label>
            </div>
          </div>

          <section className="mt-8">
            <div className="flex items-center gap-2">
              <span aria-hidden className="text-lg leading-none">
                🎢
              </span>
              <p className="text-sm font-semibold text-slate-950">Thrill tolerance</p>
            </div>
            <div className="mt-3 grid gap-3 md:grid-cols-3">
              {thrillOptions.map((option) => (
                <SelectableCard
                  key={option.value}
                  title={option.label}
                  description={option.description}
                  selected={values.thrillTolerance === option.value}
                  onClick={() => updateValues({ thrillTolerance: option.value })}
                />
              ))}
            </div>
          </section>

          <section className="mt-8">
            <div className="flex items-center gap-2">
              <span aria-hidden className="text-lg leading-none">
                🚶
              </span>
              <p className="text-sm font-semibold text-slate-950">Walking tolerance</p>
            </div>
            <div className="mt-3 grid gap-3 md:grid-cols-3">
              {walkingOptions.map((option) => (
                <SelectableCard
                  key={option.value}
                  title={option.label}
                  description={option.description}
                  selected={values.walkingTolerance === option.value}
                  onClick={() => updateValues({ walkingTolerance: option.value })}
                />
              ))}
            </div>
          </section>

          <section className="mt-8">
            <div className="flex items-center justify-between gap-3">
              <div className="flex items-center gap-2">
                <span aria-hidden className="text-lg leading-none">
                  🌟
                </span>
                <p className="text-sm font-semibold text-slate-950">Must-do experiences</p>
              </div>
              <Badge variant="neutral">{selectedMustDos.length} selected</Badge>
            </div>
            <div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">
              {catalog.mustDoOptions.map((attraction) => {
                const selected = values.mustDoRideIds.includes(attraction.id);
                return (
                  <button
                    key={attraction.id}
                    type="button"
                    onClick={() => updateValues({ mustDoRideIds: toggleSelection(values.mustDoRideIds, attraction.id) })}
                    className={cn(
                      "rounded-[24px] border px-4 py-4 text-left transition",
                      selected ? "border-[#b3d8d0] bg-cyan-50" : "border-slate-200 bg-white hover:border-[#bfd4cb]"
                    )}
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <p className="font-semibold text-slate-950">{attraction.name}</p>
                        <p className="mt-1 text-sm text-slate-500">{attraction.zone}</p>
                      </div>
                      <Badge variant={selected ? "info" : "neutral"}>{selected ? "Saved" : "Optional"}</Badge>
                    </div>
                    <p className="mt-4 text-xs uppercase tracking-[0.22em] text-slate-400">
                      Thrill {attraction.thrillLevel}/5 {attraction.kidFriendly ? "| Kid-friendly" : "| Headliner"}
                    </p>
                  </button>
                );
              })}
            </div>
          </section>

          <section className="mt-8">
            <div className="flex items-center gap-2">
              <span aria-hidden className="text-lg leading-none">
                🎠
              </span>
              <p className="text-sm font-semibold text-slate-950">Preferred ride styles</p>
            </div>
            <div className="mt-3 flex flex-wrap gap-3">
              {catalog.rideTypeOptions.map((option) => (
                <TagButton
                  key={option.value}
                  selected={values.preferredRideTypes.includes(option.value)}
                  onClick={() => updateValues({ preferredRideTypes: toggleSelection(values.preferredRideTypes, option.value) })}
                >
                  {option.label}
                </TagButton>
              ))}
            </div>
          </section>

          <section className="mt-8">
            <div className="flex items-center gap-2">
              <span aria-hidden className="text-lg leading-none">
                🍽️
              </span>
              <p className="text-sm font-semibold text-slate-950">Dining preferences</p>
            </div>
            <div className="mt-3 flex flex-wrap gap-3">
              {catalog.diningPreferenceOptions.map((option) => (
                <TagButton
                  key={option.value}
                  selected={values.diningPreferences.includes(option.value)}
                  onClick={() => updateValues({ diningPreferences: toggleSelection(values.diningPreferences, option.value) })}
                >
                  {option.label}
                </TagButton>
              ))}
            </div>
          </section>
        </div>
      </details>

      <div className="mt-6 flex flex-col gap-3 border-t border-slate-200/80 pt-6 sm:flex-row sm:items-center sm:justify-between">
        <p className="text-sm text-slate-500">Details save automatically and guide the plan.</p>
        <div className="flex flex-col gap-3 sm:flex-row">
          <Button type="button" variant="secondary" onClick={() => void handleSave()} disabled={saveState === "saving" || isGenerating}>
            Save now
          </Button>
          <Button type="button" onClick={handleGenerate} disabled={isGenerating || saveState === "saving"} data-tour-id="build-plan-action">
            {isGenerating ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : null}
            {isGenerating ? "Building plan..." : "Build plan"}
          </Button>
        </div>
      </div>
    </Card>
  );
}

function SelectableCard({
  title,
  description,
  selected,
  onClick,
}: {
  title: string;
  description: string;
  selected: boolean;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "rounded-[24px] border p-5 text-left transition",
        selected ? "border-[#b3d8d0] bg-cyan-50" : "border-slate-200 bg-white hover:border-[#bfd4cb]"
      )}
    >
      <p className="text-base font-semibold text-slate-950">{title}</p>
      <p className="mt-3 text-sm leading-7 text-slate-500">{description}</p>
    </button>
  );
}

function TagButton({
  children,
  selected,
  onClick,
}: {
  children: string;
  selected: boolean;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "rounded-full border px-4 py-2 text-sm font-semibold transition",
        selected ? "border-[#b3d8d0] bg-cyan-50 text-teal-700" : "border-slate-200 bg-white text-slate-600 hover:border-[#bfd4cb]"
      )}
    >
      {children}
    </button>
  );
}

function SnapshotCard({
  label,
  value,
  detail,
  icon: Icon,
}: {
  label: string;
  value: string;
  detail: string;
  icon: LucideIcon;
}) {
  return (
    <div className="rounded-[20px] border border-slate-200 bg-white p-4">
      <div className="flex items-center gap-3 text-slate-950">
        <div className="flex h-9 w-9 items-center justify-center rounded-[14px] bg-cyan-50 text-teal-700">
          <Icon className="h-5 w-5" />
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.22em] text-slate-400">{label}</p>
          <p className="mt-1 text-sm font-semibold text-slate-950">{value}</p>
        </div>
      </div>
      <p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p>
    </div>
  );
}















